// Display metadata for feature types (glyphs + labels), shared by the timeline,
// browser tree, and toolbar.
import type { FeatureType } from "../types";

export const FEATURE_META: Record<FeatureType, { glyph: string; label: string }> = {
  sketch: { glyph: "✎", label: "Sketch" },
  extrude: { glyph: "⬆", label: "Extrude" },
  fillet: { glyph: "◜", label: "Fillet" },
  chamfer: { glyph: "◣", label: "Chamfer" },
  "press-pull": { glyph: "⤒", label: "Press/Pull" },
  deleteFace: { glyph: "⌫", label: "Delete Face" },
  mirror: { glyph: "⇋", label: "Mirror" },
  revolve: { glyph: "↻", label: "Revolve" },
  loft: { glyph: "≋", label: "Loft" },
  sweep: { glyph: "⤳", label: "Sweep" },
  datumPlane: { glyph: "▱", label: "Datum Plane" },
  import: { glyph: "⤓", label: "Import" },
  split: { glyph: "✂", label: "Split Body" },
  combine: { glyph: "⊕", label: "Combine" },
  box: { glyph: "▢", label: "Box" },
  cylinder: { glyph: "⬭", label: "Cylinder" },
  sphere: { glyph: "◯", label: "Sphere" },
  shell: { glyph: "⬚", label: "Shell" },
  draft: { glyph: "◹", label: "Draft" },
  patternRect: { glyph: "⁙", label: "Rect Pattern" },
  patternCircular: { glyph: "❋", label: "Circular Pattern" },
  simplifyMesh: { glyph: "⬡", label: "Simplify Mesh" },
  cleanUp: { glyph: "🧹", label: "Clean Up" },
  scale: { glyph: "⤢", label: "Scale" },
  move: { glyph: "✥", label: "Move" },
  removeBody: { glyph: "🗑", label: "Remove Body" },
  texture: { glyph: "▦", label: "Texture" },
};
